- hosts: localhost
  become: true
  gather_facts: yes
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    - name: System details
      debug:
        msg: "{{ ansible_facts['lsb']['codename'] }}"
    - name: User id
      debug:
        msg: "{{ ansible_user_id }}"

    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: username_on_the_host
      tags: always

    - debug: var=username_on_the_host
      tags: always


    - import_tasks: tasks/essential_tools.yml
      tags: essential
    - import_tasks: tasks/convenient_tools.yml
      tags: convenient
    - import_tasks: tasks/convenient_keybindings.yml
      tags: keybindings
    - import_tasks: tasks/docker.yml
      tags: docker
    - import_tasks: tasks/create_standard_dirs.yml
      tags: dirs
    - import_tasks: tasks/gui_tweaks.yml
      tags: gui


