- hosts: localhost
  become: true
  gather_facts: yes
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    - name: System details
      debug:
        msg: "{{ ansible_facts['lsb']['codename'] }}"
    - name: User id
      debug:
        msg: "{{ ansible_user_id }}"

    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: username_on_the_host

    - debug: var=username_on_the_host


    - include_tasks: tasks/essential_tools.yml
    - include_tasks: tasks/convenient_tools.yml
    - include_tasks: tasks/convenient_keybindings.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/create_standard_dirs.yml
    - include_tasks: tasks/gui_tweaks.yml


