- name: Install convenient packages - apt
  apt: name={{item}}
  with_items:
    - terminator
    - silversearcher-ag
    - flameshot
    - chromium-browser

- name: Add AppImageLauncher PPA repository
  apt_repository:
    repo: ppa:appimagelauncher-team/stable
    state: present
    update_cache: yes

- name: Install AppImageLauncher
  apt:
    name: appimagelauncher
    state: present

- name: Check if Cursor is already installed
  become: false
  command: which cursor
  register: cursor_installed
  failed_when: false
  changed_when: false

- name: Download Cursor .deb package
  become: false
  get_url:
    url: https://api2.cursor.sh/updates/download/golden/linux-x64-deb/cursor/1.7
    dest: /tmp/cursor.deb
    mode: '0644'
  when: cursor_installed.rc != 0

- name: Install Cursor from .deb package
  apt:
    deb: /tmp/cursor.deb
  when: cursor_installed.rc != 0

- name: Check if Claude is already installed
  become: false
  command: which claude
  register: claude_installed
  failed_when: false
  changed_when: false

- name: Install Claude Desktop
  become: false
  shell: curl -fsSL https://claude.ai/install.sh | bash
  when: claude_installed.rc != 0

- name: Clone magicmonty git bash prompt
  ansible.builtin.git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: /home/{{ username_on_the_host.stdout }}/.bash-git-prompt
    depth: 1

- name: Check if username_on_the_host is root, if yes then exit
  ansible.builtin.fail: msg="Exiting, need to be non-root for this to work. Try run without sudo"
  when: username_on_the_host.stdout == "root"

- name: Add block to bashrc for magicmonty
  blockinfile:
    path: /home/{{ username_on_the_host.stdout }}/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK magic-monty"
    block: |
      if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
          GIT_PROMPT_ONLY_IN_REPO=1
          source "$HOME/.bash-git-prompt/gitprompt.sh"
      fi
    state: present
    create: true



