- name: Install convenient packages - apt
  apt: name={{item}}
  with_items:
    - terminator
    - silversearcher-ag
    - flameshot
    - chromium-browser

- name: Install convenient packages - snap
  snap: name={{item}}
  with_items:
    - code

- name: Clone magicmonty git bash prompt
  ansible.builtin.git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: /home/{{ username_on_the_host.stdout }}/.bash-git-prompt
    depth: 1

- name: Check if username_on_the_host is root, if yes then exit
  ansible.builtin.fail: msg="Exiting, need to be non-root for this to work. Try run without sudo"
  when: username_on_the_host.stdout == "root"

- name: Add block to bashrc for magicmonty
  blockinfile:
    path: /home/{{ username_on_the_host.stdout }}/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK magic-monty"
    block: |
      if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
          GIT_PROMPT_ONLY_IN_REPO=1
          source "$HOME/.bash-git-prompt/gitprompt.sh"
      fi
    state: present
    create: true


#TODO
# set terminator configuration file
# vscode settings install


