- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    state: present

- name: Install latest docker and requirements
  apt: name={{item}}
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Install Docker Module for Python
  pip:
    name: docker

- name: check docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: Make sure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Check if username_on_the_host is root, if yes then exit
  ansible.builtin.fail: msg="Exiting, need to be non-root for this to work. Try run without sudo"
  when: username_on_the_host.stdout == "root"

- name: Adding user to docker group
  user:
    name: "{{ username_on_the_host.stdout }}"
    groups: docker
    append: yes
  register: add_user_result

- name: Reboot after adding user to group first time
  ansible.builtin.fail: msg="We need to reboot now to make the group take effect. Reboot and then run again"
  when: (add_user_result.changed == True) 

- name: Reset ssh connection to allow user changes to affect ansible user # Doesn't work for local connection
  ansible.builtin.meta:
    reset_connection
