- name: Install required packages
  apt: name={{item}}
  with_items:
    - gnome-tweaks
    - gir1.2-gtop-2.0
    - gir1.2-nm-1.0
    - gir1.2-clutter-1.0
    - gnome-system-monitor
    - gnome-shell-extension-prefs

- name: automatic timezone
  become: false   # VERY IMPORTANT
  community.general.dconf:
    key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"

- name: clock show date
  become: false
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: clock format
  become: false
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"

# Note this this is a PIA to get installed on Ubuntu 22.04, its semi unsupported
# I have made it work as below but this will likely not transfer well to other Ubuntu
# versions so solve that one to make it portable if you would like.
# Here are some clues
# - This should work for Ubuntu-18 https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet
# - This is where i got the download link for 22.04. You have to find your gnome-shell --version first https://extensions.gnome.org/extension/3010/system-monitor-next/
# - Here's the info for installing a manually downloaded gnome-extension. TLDR, unzip and rename the folder to be the same as the UUID in the manifest https://www.debugpoint.com/manual-installation-gnome-extension/

- name: Download system monitor extension
  become: false
  ansible.builtin.get_url:
    dest: /tmp
    url: https://extensions.gnome.org/extension-data/system-monitor-nextparadoxxx.zero.gmail.com.v39.shell-extension.zip

- name: Ensure extensions directory exists
  become: false
  file:
    path: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/
    state: directory

- name: Move extension correct location
  become: false
  ansible.builtin.copy:
    src: /tmp/system-monitor-nextparadoxxx.zero.gmail.com.v39.shell-extension.zip
    dest: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/system-monitor-nextparadoxxx.zero.gmail.com.v39.shell-extension.zip
  register: added_gnome_extension

- name: Ensure extract system monitor directory exists
  become: false
  file:
    path: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com
    state: directory

- name: Extract system monitor
  become: false
  ansible.builtin.unarchive:
    src: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/system-monitor-nextparadoxxx.zero.gmail.com.v39.shell-extension.zip
    dest: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com


- name: Download tactile extension
  become: false
  ansible.builtin.get_url:
    dest: /tmp
    url: https://extensions.gnome.org/extension-data/tactilelundal.io.v27.shell-extension.zip

- name: Move tactile extension to correct location
  become: false
  ansible.builtin.copy:
    src: /tmp/tactilelundal.io.v27.shell-extension.zip
    dest: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/tactilelundal.io.v27.shell-extension.zip
  register: added_tactile_extension

- name: Ensure extract tactile directory exists
  become: false
  file:
    path: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/tactile@lundal.io
    state: directory

- name: Extract tactile extension
  become: false
  ansible.builtin.unarchive:
    src: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/tactilelundal.io.v27.shell-extension.zip
    dest: /home/{{ username_on_the_host.stdout }}/.local/share/gnome-shell/extensions/tactile@lundal.io

- name: Create helper script to reload GNOME shell
  become: false
  copy:
    content: |
      #!/bin/bash
      echo "Reloading GNOME Shell..."
      echo "If you're on X11, this will restart GNOME Shell."
      echo "If you're on Wayland, you'll need to log out and log back in."
      if [ "$XDG_SESSION_TYPE" = "x11" ]; then
        killall -3 gnome-shell
        echo "GNOME Shell restarted!"
      else
        echo "You're on Wayland. Please log out and log back in."
      fi
    dest: /tmp/reload-gnome-shell.sh
    mode: '0755'
  when: added_gnome_extension.changed == True or added_tactile_extension.changed == True

- name: Notify user about GNOME extension installation
  ansible.builtin.debug:
    msg:
      - "=========================================="
      - "WARNING: GNOME extension(s) have been installed."
      - "To activate the extensions, you need to reload GNOME Shell:"
      - ""
      - "  X11 users: Press Alt+F2, type 'r', and press Enter"
      - "  OR run: /tmp/reload-gnome-shell.sh"
      - ""
      - "  Wayland users: Log out and log back in"
      - "  To re-run just this section run: ansible-playbook local.yml -K --tags gui"
      - "=========================================="
  when: added_gnome_extension.changed == True or added_tactile_extension.changed == True

- name: Enable system monitor extension
  become: false
  ansible.builtin.command: gnome-extensions enable system-monitor-next@paradoxxx.zero.gmail.com

- name: Enable tactile extension
  become: false
  ansible.builtin.command: gnome-extensions enable tactile@lundal.io